### ISSUE TITLE
Hide Buttons

### ISSUE THREAD

**Issue by zipatton** [undefined06855/StuffMod#12]
# An option to hide both Achievements and Stats buttons.

> [!NOTE]
>
> ![20240314130300_1](https://github.com/undefined06855/GDTweaks/assets/155669622/43afae49-1a53-4ac6-9c92-c2dc49e0c379)
> > Concept Image

**Comment by zipatton** [comment]
also, i learned how to use github markdown

**Comment by zipatton** [comment]
> [!WARNING]
just found out this feature already exists in the settings for JunkHider. Might be better to have JunkHider be a suggested mod.
> 
> This also exists in Hide+

**Comment by undefined06855** [comment]
the problem is that suggested mods incline the user to download them, i'm tempted to also remove betterinfo and textureldr from the suggested mods since they aren't needed

if I have the time I might but don't get your hopes up since other mods obviously do this as well

**Comment by undefined06855** [comment]
i might as well do this now

**Comment by undefined06855** [comment]
Added in v1.12.0
