### ISSUE TITLE
Add Geode Tags

### ISSUE THREAD

**Issue by zipatton** [undefined06855/StuffMod#13]
Nobody uses the tag filter thing in geode but it would look a bit better with them. I don't know how to have them added but I think it would be a good idea.

**Comment by undefined06855** [comment]
there are tags, are they not showing up for you?

**Comment by zipatton** [comment]
> there are tags, are they not showing up for you?

Nope. I'm running Geode v2.0.0-BETA.22 on Windows 11

**Comment by undefined06855** [comment]
tags only show if you dont have the mod installed for some reason

![image](https://github.com/undefined06855/GDTweaks/assets/98057141/d228aacb-a75e-41a4-b84a-b2857fdedd8a)
uninstalled

![image](https://github.com/undefined06855/GDTweaks/assets/98057141/0de32e09-e3f1-481a-89a9-63eb6ae2d7cf)
installed
