### ISSUE TITLE
Remove player from main menu doesn't remove ship fire

### ISSUE THREAD

**Issue by phobozo** [undefined06855/StuffMod#15]
![image](https://github.com/undefined06855/GDTweaks/assets/170972691/16410bdd-60db-47db-be4f-6ff44513741f)

**Comment by undefined06855** [comment]
ngl I do know about this but have been putting off fixing it until someone made an issue about it, I'll probably fix this soon then

**Comment by undefined06855** [comment]
should be fixed in 1.12.4-alpha.2
