### ISSUE TITLE
Option for changing the Geode button texture

### ISSUE THREAD

**Issue by derpydudee** [undefined06855/StuffMod#19]
I think it would be cool to have an option to change the Geode button texture in the main menu to the coloured logo (image below)

Can't do any screenshotting right now because I play GD on a different device that I don't have on me right now
![88206422](https://github.com/undefined06855/GDTweaks/assets/147573028/f1fd24ef-06e6-4a9f-97f5-a5ddf136c7ed)

**Comment by undefined06855** [comment]
Added in v1.12.5
![image](https://github.com/undefined06855/GDTweaks/assets/98057141/a46291c8-c881-4637-8d0b-933b5f559c46)
(it looked really weird on its own so I added a border like the other buttons)
