### ISSUE TITLE
Enabling 'Remove "tap lock for more info!" message' makes the right arrow in the icon kit disappear

### ISSUE THREAD

**Issue by AuthentiCuber** [undefined06855/StuffMod#2]

**Comment by undefined06855** [comment]
i need to rework the entire icon kit stuff, there's more things that modify it than I thought and there's quite a few incompatibilities

**Comment by undefined06855** [comment]
can you tell me what mods you've installed, I think it should be fixed but I need to check

**Comment by AuthentiCuber** [comment]
It's fixed for me

**Comment by AuthentiCuber** [comment]
It's fixed for me
