### ISSUE TITLE
[Feature Request] Move Daily Chest on Main Menu to Bottom Right

### ISSUE THREAD

**Issue by torzod** [undefined06855/StuffMod#3]
Having an option to move the daily chest on the main menu to the bottom right of the screen, symmetrical with the account button (with the "Move account icon to the corner" setting enabled) would be nice to make the main menu symmetrical and would make it look a lot cleaner. Here is a crappy mockup.
![image](https://github.com/undefined06855/GDTweaks/assets/29359401/1b11edb9-2982-4bb4-ad40-87e68bf44170)
It might look better were the daily chest icon to be scaled up, though i'm not sure how easy that would be.

**Comment by undefined06855** [comment]
Added in v1.8.0!
