### ISSUE TITLE
Replace map packs with hall of fame

### ISSUE THREAD

**Issue by Epyx15** [undefined06855/StuffMod#4]
I like the option to remove map packs but then it makes the creator layer look cursed so my suggestion is to add a option to replace map packs with hall of fame with this the menu won't look cursed anymore and we will be able to access the hall of fame without better info

**Comment by undefined06855** [comment]
good idea, I'll take a look at BetterInfo to see what cvolton does to add the hall of fame back in

**Comment by undefined06855** [comment]
added in [v1.9.0](https://github.com/undefined06855/GDTweaks/commit/91bebddd051fdf3e01d94637104ea250e25192d6)
