### ISSUE TITLE
hall of fame

### ISSUE THREAD

**Issue by undefined06855** [undefined06855/StuffMod#6]
![Screenshot_2024-02-26-15-31-22-276_com.geode.launcher.jpg](https://github.com/undefined06855/GDTweaks/assets/98057141/de878b36-bf9e-4f29-b019-1516defac681)

**Comment by undefined06855** [comment]
literally still no idea why this is happening, might have to force gd to use the same texture as different resolutions or something like minecraftify does

**Comment by Helloausername** [comment]
same to me

**Comment by undefined06855** [comment]
oh my god im so stupid i just fixed this
