### ISSUE TITLE
BetterInfo button layer issue

### ISSUE THREAD

**Issue by zipatton** [undefined06855/StuffMod#8]
# BetterInfo button is layered beneath corner art
### May be a conflicting mod issue
![20240308121853_1](https://github.com/undefined06855/GDTweaks/assets/155669622/4d80b2b4-8625-46eb-9d3e-6f7d9e29df38)

**Comment by undefined06855** [comment]
i swear i literally just fixed this in 1.9.2, what mods do you have?

**Comment by undefined06855** [comment]
wait i think i broke it in 1.9.2 tf

**Comment by undefined06855** [comment]
nvm i broke it in 1.9.1, didnt realise, then thought i fixed it in 1.9.2

**Comment by undefined06855** [comment]
ok i fixed it in 1.9.3

**Comment by zipatton** [comment]
Thank goodness I didn't have to list my 11 mods again
