### ISSUE TITLE
Hide Orb Stat on Level Search

### ISSUE THREAD

**Issue by zipatton** [undefined06855/StuffMod#9]
Just a shower thought, but an option to hide the amount of orbs collected on a level (in the list) would be kind of nice for other mods like Level Thumbnails.

**Comment by undefined06855** [comment]
yeah sure ill add it in 1.10 or something if i remember

**Comment by undefined06855** [comment]
it was much easier than I thought, I'm also adding categories to the settings so it's easier to sift through in 1.10 as well
